language: rust
dist: xenial
cache: cargo

install:
- bundle install

# Build and deploy the site to the S3 bucket on push to master, unless PR
script:
  - cargo run && bundle exec jekyll build
branches:
  only:
  - master

deploy:
  provider: script
  script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd _site && ../../rust_out)
  skip_cleanup: true
  on:
    branch: master
