language: rust
dist: xenial

env:
  RUSTINFRA_DEPLOY_DIR: book
  RUSTINFRA_CLOUDFRONT_DISTRIBUTION: E12A3GKHZSREHP
import:
  - rust-lang/simpleinfra/travis-configs/static-websites.yml

cache:
  directories:
    # cache: cargo
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

before_install:
  - sudo apt-get update
  - sudo apt-get -y install jq curl
  # Retrieve latest mdbook release.
  - RELEASES="$(curl https://api.github.com/repos/rust-lang/mdbook/releases/latest)"
  # Filter to just the url for the `unknown-linux-gnu` release.
  - URL=$(echo $RELEASES | jq -r '.assets[] as $in | $in.name | match("unknown-linux-gnu") | $in.browser_download_url')
  # Download and untar the binary into the path.
  - curl -L $URL | sudo tar xz -C /usr/local/bin

script:
  - mdbook build
  - cp website_config.json book/
branches:
  only:
    - master
