language: rust
dist: xenial
cache: cargo

env:
  RUSTINFRA_DEPLOY_DIR: _site
import:
  - rust-lang/simpleinfra/travis-configs/static-websites.yml@travis-configs

install:
- bundle install

script:
  - cargo run && bundle exec jekyll build
branches:
  only:
  - master
