language: rust
dist: xenial

env:
  RUSTINFRA_DEPLOY_DIR: _site
  RUSTINFRA_CLOUDFRONT_DISTRIBUTION: E12A3GKHZSREHP
import:
  - rust-lang/simpleinfra/travis-configs/static-websites.yml

cache:
  directories:
    # cache: cargo
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target
    # cache: bundler
    - $TRAVIS_BUILD_DIR/vendor/bundle

install:
  - bundle install --path vendor/bundle

script:
  - cargo run && bundle exec jekyll build
branches:
  only:
  - master
