language: rust
dist: xenial

env:
  RUSTINFRA_DEPLOY_DIR: book
  RUSTINFRA_CLOUDFRONT_DISTRIBUTION: E12A3GKHZSREHP
import:
  - rust-lang/simpleinfra/travis-configs/static-websites.yml

cache:
  directories:
    # cache: cargo
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

before_script:
  # TODO: Installing mdbook from crates.io takes quite a long time. This could
  # be reduced by downloading the release from GitHub directly.
  - mdbook -V || cargo install mdbook --vers '^0.3.0'
script:
  - mdbook build
branches:
  only:
  - master
