language: rust
dist: xenial
cache: cargo

install:
- bundle install

script:
  - cargo run && bundle exec jekyll build
  # Ensure GitHub pages doesn't mangle with the build output
  - touch _site/.nojekyll
branches:
  only:
  - master

deploy:
  provider: script
  script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd _site && ../rust_out)
  skip_cleanup: true
  on:
    branch: master
