language: rust
dist: xenial

install:
- bundle install

# Build and deploy the site to the S3 bucket on push to master, unless PR
script:
  - cargo run && bundle exec jekyll build
branches:
  only:
  - master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: _site
  on:
    branch: master
