name: The Rust Programming Language
stable: "1.31.1"
stable_date: "2018-12-20"
stable_blog: "https://blog.rust-lang.org/2018/12/20/Rust-1.31.1.html"
stable_full_version: "rustc 1.31.1 (b6c32da9b 2018-12-18)"
beta: "1.32"
beta_date: "2019-01-18"
nightly: "1.33"
channels:
  - name: "stable"
    vers: "1.31.0"
    package: "1.31.0"
  - name: "beta"
    vers: "1.32"
    package: "beta"
  - name: "nightly"
    vers: "1.33"
    package: "nightly"
