name: The Rust Programming Language
stable: "1.32.0"
stable_date: "2019-01-17"
stable_blog: "https://blog.rust-lang.org/2019/01/17/Rust-1.32.0.html"
stable_full_version: "rustc 1.32.0 (9fda7c223 2019-01-16)"
beta: "1.33"
beta_date: "2019-01-18"
nightly: "1.33"
channels:
  - name: "stable"
    vers: "1.32.0"
    package: "1.32.0"
  - name: "beta"
    vers: "1.33"
    package: "beta"
  - name: "nightly"
    vers: "1.33"
    package: "nightly"
