name: The Rust Programming Language
stable: "1.30.1"
stable_date: "2018-11-08"
stable_blog: "https://blog.rust-lang.org/2018/11/08/Rust-1.30.1.html"
stable_full_version: "rustc 1.30.1 (1433507eb 2018-11-07)"
beta: "1.31"
beta_date: "2018-12-06"
nightly: "1.32"
channels:
  - name: "stable"
    vers: "1.30.1"
    package: "1.30.1"
  - name: "beta"
    vers: "1.31"
    package: "beta"
  - name: "nightly"
    vers: "1.32"
    package: "nightly"
