name: The Rust Programming Language
stable: "1.33.0"
stable_date: "2019-02-28"
stable_blog: "https://blog.rust-lang.org/2019/02/28/Rust-1.33.0.html"
stable_full_version: "rustc 1.33.0 (2aa4c46cf 2019-02-28)"
beta: "1.34"
beta_date: "2019-04-11"
nightly: "1.35"
channels:
  - name: "stable"
    vers: "1.33.0"
    package: "1.33.0"
  - name: "beta"
    vers: "1.34"
    package: "beta"
  - name: "nightly"
    vers: "1.35"
    package: "nightly"
